### ISSUE TITLE
Flex component does not support flex items styling within container

### ISSUE THREAD

**Issue by KalachevDev** [gravity-ui/uikit#1064]
For example,
```jsx
export function FlexLayout() {
    return (
        <Flex>
            <div>First child</div>
            <div>Second child</div>
            <div style={{marginLeft: 'auto'}}>Third child</div>
        </Flex>
    );
}
```

will result into

```jsx
<div class="yc-flex" style="display: flex;">
  <div class="yc-flex__wr">
    <div>First child</div>
  </div>
  <div class="yc-flex__wr">
    <div>Second child</div>
  </div>
  <div class="yc-flex__wr">
    <div style="margin-left: 'auto';">Third child</div>
  </div>
</div>
```

therefore it's not possible to align third element within `Flex` container. Also, per [reactdev documentation](https://reactdev.ru/reference/Children/), `React.Children` usage might lead to fragile code, maybe it worth it to consider using something like `<Flex><Flex.Item /* put styles here */>First child</Flex.Item></Flex>`?

**Comment by IsaevAlexandr** [comment]
Hi!
Think that you use a `Flex` component with `space` prop, because this is the only way to get such a result as in your example.
https://github.com/gravity-ui/uikit/blob/136e3a7a1e83701aaad5a2fb6f4a877ad0b12975/src/components/layout/Flex/Flex.tsx#L204-L209

`Space` prop needed only for old browsers where `gap` property doesn't work and it's will be deprecated in near future (i hope). So you can use `gap` property or implement spacing between flex items by you self to abandon the wrapper elements

**Comment by KalachevDev** [comment]
@IsaevAlexandr I didn't think of this option. I looked into [storybook](https://preview.gravity-ui.com/uikit/?path=/docs/layout--docs#flex) and those examples made me think that `space` is the only right option to define spacing.


Another thing on browsers support - `@gravity-ui/browserlist` says that we only support last 2 major versions of Safari -> flex-gap should be legal to use @amje or we should probably change browserlist-config.

Closing the issue then, thanks again @IsaevAlexandr
